name: GitHub Profile Trophy

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Trophy
        run: curl "${{ secrets.TROPHY_SERVER }}/?username=nekodayo2222&theme=dracula&column=-1" -o trophy.svg 
      - name: Setup Git
        run: |
          git config user.name trophy-kun[bot]
          git config user.email gh-actions-noreply@neko-room.com
      - name: Update Repository
        run: |
          git add trophy.svg
          git commit -m "Update trophies"
          git push
          
